# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Beman pre-commit check'
on:
  workflow_call:
jobs:
  pre-commit-push:
    name: Pre-Commit check on Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: pre-commit/action@v3.0.1

  pre-commit-pr:
    name: Pre-Commit check on PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}

    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # pull_request_target checkout the base of the repo
        # We need to checkout the actual pr to lint the changes.
      - name: Checkout pr
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: pre-commit/action@v3.0.1

        # Review dog posts the suggested change from pre-commit to the pr.
      - name: suggester / pre-commit
        uses: reviewdog/action-suggester@v1
        if: ${{ failure() && steps.run-pre-commit.conclusion == 'failure' }}
        with:
          tool_name: pre-commit
          level: warning
          reviewdog_flags: "-fail-level=error"
